### ISSUE TITLE
error G837C20CB: 'MenuItem' is imported from both 'package:flutter/src/widgets/platform_menu_bar.dart' and 'package:menu_base/src/menu_item.dart'. 

### ISSUE THREAD

**Issue by jonahzheng** [leanflutter/menu_base#3]
error G837C20CB: 'MenuItem' is imported from both 'package:flutter/src/widgets/platform_menu_bar.dart' and 'package:menu_base/src/menu_item.dart'.

**Comment by lijy91** [comment]
Please hide MenuItem when importing 'package:flutter/material.dart';

```dart
import 'package:flutter/material.dart' hide MenuItem;
```

**Comment by jonahzheng** [comment]
这其实是 tray_manager引用了menu_base报的错，在flutter3.0下

**Comment by lijy91** [comment]
> 这其实是 tray_manager引用了menu_base报的错，在flutter3.0下

tray_manager 的 README 也有说明，需要在导入时 hide flutter 的 MenuItem   https://github.com/leanflutter/tray_manager#usage
